/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface ArticleShareLinkCreate {
  /** @pattern ^(default|manual)$ */
  url_mode?: string;
  custom_url?: string | null;
  /** @pattern ^(default|manual)$ */
  thumbnail_mode?: string;
  thumbnail_url?: string | null;
}
