/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface ArticleShareLinkResponse {
  share_id: string;
  expires_at?: string | null;
  share_url: string;
  share_slug: string;
  canonical_share_url: string;
  url_mode?: string;
  custom_url?: string | null;
  thumbnail_mode?: string;
  thumbnail_url?: string | null;
}
