/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface MyShareLinkItem {
  share_id: string;
  article_id: string;
  article_title: string;
  article_url?: string | null;
  share_slug: string;
  canonical_share_url: string;
  public_url?: string | null;
  view_count?: number;
  empathy_count?: number;
  comment_count?: number;
  summary_preview?: string | null;
  concepts?: string[];
  content_type?: string | null;
  thumbnail_url?: string | null;
  created_at: string;
  expires_at?: string | null;
}
