/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export type PostSharedArticleCommentEmpathyApiArticlesShareShareIdCommentsCommentIdEmpathyPostParams = {
/**
 * @minLength 1
 */
token: string;
};
