/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */
import type { SharedArticleSharerResponse } from './sharedArticleSharerResponse';
import type { SharedArticleSummaryResponseTypeMetadata } from './sharedArticleSummaryResponseTypeMetadata';

export interface SharedArticleSummaryResponse {
  share_id: string;
  share_slug: string;
  share_sid: string;
  canonical_share_path: string;
  article_id: string;
  title: string;
  source: string;
  url?: string | null;
  created_at: string;
  summary: string;
  markdown_note?: string | null;
  key_points: string[];
  concepts: string[];
  reading_time_minutes?: number | null;
  language?: string | null;
  content_type: string;
  type_metadata: SharedArticleSummaryResponseTypeMetadata;
  empathy_count?: number;
  viewer_has_empathy?: boolean;
  sharer: SharedArticleSharerResponse;
  url_mode?: string;
  custom_url?: string | null;
  thumbnail_mode?: string;
  thumbnail_url?: string | null;
}
