/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface SharedArticleCommentResponse {
  id: string;
  author_name: string;
  author_image?: string | null;
  author_user_id?: string | null;
  parent_comment_id?: string | null;
  content: string;
  created_at: string;
  empathy_count?: number;
  viewer_has_empathy?: boolean;
  replies?: SharedArticleCommentResponse[];
}
