/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface SharedArticleCommentUpdate {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  content: string;
}
