/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * fullstack-starter-api
 * OpenAPI spec version: 0.1.0
 */

export interface SharedArticleSharerResponse {
  name?: string | null;
  image?: string | null;
}
