import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SOURCE_DIR = join(ROOT, "src");
const WEB_OUTPUT_DIR = resolve(ROOT, "../../apps/web/src/config/messages");
const MOBILE_OUTPUT_DIR = resolve(ROOT, "../../apps/mobile/lib/i18n/messages");
const EXTENSION_OUTPUT_DIR = resolve(ROOT, "../../apps/extension/src/lib/i18n");

interface ArbFile {
  [key: string]: string | object;
}

interface NestedJson {
  [key: string]: string | NestedJson;
}

function parseArgs(): { target: "all" | "web" | "mobile" | "extension" } {
  const args = process.argv.slice(2);
  const targetIndex = args.indexOf("--target");
  if (targetIndex !== -1 && args[targetIndex + 1]) {
    const target = args[targetIndex + 1];
    if (target === "web" || target === "mobile" || target === "extension") {
      return { target };
    }
  }
  return { target: "all" };
}

function readArbFiles(): Map<string, ArbFile> {
  const files = new Map<string, ArbFile>();
  const arbFiles = readdirSync(SOURCE_DIR).filter((f) => f.endsWith(".arb"));

  for (const file of arbFiles) {
    const content = readFileSync(join(SOURCE_DIR, file), "utf-8");
    const locale = file.replace(".arb", "");
    files.set(locale, JSON.parse(content));
  }

  return files;
}

const COMMON_KEYS = ["loading", "error", "save", "cancel", "confirm", "delete", "retry"];

const EXTENSION_KEYS = [
  "extHeaderTitle", "extHeaderSubtitle",
  "extLoginTitle", "extLoginSubtitle",
  "extLoginFeature1", "extLoginFeature2", "extLoginFeature3", "extLoginButton",
  "extLoadingAuth", "extLoadingExtract",
  "extSaveButton", "extSaving",
  "extSaveSuccessTitle", "extSaveSuccessSubtitle", "extViewDashboard",
  "extErrorTitle", "extTryAgain", "extMinRead",
];

function isArbMetadataKey(key: string): boolean {
  return key.startsWith("@@") || key.startsWith("@");
}

function arbToNestedJson(arb: ArbFile): NestedJson {
  const result: NestedJson = {};

  for (const [key, value] of Object.entries(arb)) {
    if (isArbMetadataKey(key)) {
      continue;
    }

    if (EXTENSION_KEYS.includes(key)) {
      continue;
    }

    if (COMMON_KEYS.includes(key)) {
      if (!result.common) {
        result.common = {};
      }
      (result.common as NestedJson)[key] = value as string;
    } else if (key === "appTitle") {
      result.title = value as string;
    } else {
      result[key] = value as string;
    }
  }

  return result;
}

function arbToMobileArb(arb: ArbFile, locale: string): ArbFile {
  const result: ArbFile = { "@@locale": locale };

  for (const [key, value] of Object.entries(arb)) {
    if (key === "@@locale") continue;
    result[key] = value;
  }

  return result;
}

function arbToExtensionTs(arbFiles: Map<string, ArbFile>): string {
  const locales: Record<string, Record<string, string>> = {};

  for (const [locale, arb] of arbFiles) {
    const entries: Record<string, string> = {};
    for (const [key, value] of Object.entries(arb)) {
      if (isArbMetadataKey(key)) continue;
      if (EXTENSION_KEYS.includes(key)) {
        entries[key] = value as string;
      }
    }
    locales[locale] = entries;
  }

  const lines = [
    "// Auto-generated by i18n build script. Do not edit manually.",
    "",
    `const translations = ${JSON.stringify(locales, null, 2)} as const;`,
    "",
    "type TranslationKey = keyof typeof translations.en;",
    "",
    "function getLocale(): keyof typeof translations {",
    "  try {",
    "    const lang = chrome?.i18n?.getUILanguage?.() ?? navigator.language;",
    "    if (lang.startsWith('ko')) return 'ko';",
    "    if (lang.startsWith('ja')) return 'ja';",
    "    return 'en';",
    "  } catch {",
    "    return 'en';",
    "  }",
    "}",
    "",
    "export function t(key: TranslationKey): string {",
    "  const locale = getLocale();",
    "  return translations[locale]?.[key] ?? translations.en[key];",
    "}",
    "",
    "export type { TranslationKey };",
    "",
  ];

  return lines.join("\n");
}

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function cleanDir(dir: string): void {
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true });
  }
  mkdirSync(dir, { recursive: true });
}

function deepMerge(target: NestedJson, source: NestedJson): NestedJson {
  const result = { ...target };
  for (const [key, value] of Object.entries(source)) {
    if (typeof value === "object" && value !== null && typeof result[key] === "object" && result[key] !== null) {
      result[key] = deepMerge(result[key] as NestedJson, value as NestedJson);
    } else {
      result[key] = value;
    }
  }
  return result;
}

function buildWeb(arbFiles: Map<string, ArbFile>): void {
  console.log("Building web i18n files...");
  ensureDir(WEB_OUTPUT_DIR);

  for (const [locale, arb] of arbFiles) {
    const nested = arbToNestedJson(arb);
    const outputPath = join(WEB_OUTPUT_DIR, `${locale}.json`);

    let existing: NestedJson = {};
    if (existsSync(outputPath)) {
      try {
        existing = JSON.parse(readFileSync(outputPath, "utf-8"));
      } catch {
        existing = {};
      }
    }

    const merged = deepMerge(existing, nested);
    writeFileSync(outputPath, `${JSON.stringify(merged, null, 2)}\n`);
    console.log(`  Created: ${outputPath}`);
  }
}

function buildMobile(arbFiles: Map<string, ArbFile>): void {
  console.log("Building mobile i18n files...");
  ensureDir(MOBILE_OUTPUT_DIR);

  for (const [locale, arb] of arbFiles) {
    const mobileArb = arbToMobileArb(arb, locale);
    const outputPath = join(MOBILE_OUTPUT_DIR, `app_${locale}.arb`);
    writeFileSync(outputPath, `${JSON.stringify(mobileArb, null, 2)}\n`);
    console.log(`  Created: ${outputPath}`);
  }
}

function buildExtension(arbFiles: Map<string, ArbFile>): void {
  console.log("Building extension i18n files...");
  ensureDir(EXTENSION_OUTPUT_DIR);

  const tsContent = arbToExtensionTs(arbFiles);
  const outputPath = join(EXTENSION_OUTPUT_DIR, "index.ts");
  writeFileSync(outputPath, tsContent);
  console.log(`  Created: ${outputPath}`);
}

function main(): void {
  const { target } = parseArgs();
  console.log(`i18n build started (target: ${target})`);

  const arbFiles = readArbFiles();
  console.log(`Found ${arbFiles.size} locale(s): ${[...arbFiles.keys()].join(", ")}`);

  if (target === "all" || target === "web") {
    buildWeb(arbFiles);
  }

  if (target === "all" || target === "mobile") {
    buildMobile(arbFiles);
  }

  if (target === "all" || target === "extension") {
    buildExtension(arbFiles);
  }

  console.log("i18n build completed!");
}

main();
