# /// script
# requires-python = ">=3.12"
# ///
# How to run: python3 -m unittest scripts.quality.tests.test_generated_drift -v

from __future__ import annotations

import os
import stat
import subprocess
import unittest
from pathlib import Path
from typing import Final

from scripts.quality.contracts.json_boundary import JsonObject
from scripts.quality.tests.generated_drift_test_support import DriftRepo, first_pair, json_object, parse_result

SCRIPT: Final = Path(__file__).resolve().parents[1] / "generated_drift.py"
CLEAN_GENERATOR: Final = "from pathlib import Path; p=Path('generated/result.txt'); p.parent.mkdir(exist_ok=True); p.write_text('generated\\n')\n"


def run_gate(repo: DriftRepo, matrix: Path) -> tuple[subprocess.CompletedProcess[str], JsonObject]:
    completed = subprocess.run(
        ("python3", str(SCRIPT), "--repo", str(repo.root), "--revision", "HEAD", "--matrix", str(matrix), "--json"),
        check=False, capture_output=True, text=True,
    )
    return completed, parse_result(completed.stdout)


class GeneratedDriftTests(unittest.TestCase):
    def test_clean_pair_when_generator_reproduces_complete_manifest(self) -> None:
        # Given: committed generated bytes match deterministic generator output.
        with DriftRepo() as repo:
            repo.write_generator(CLEAN_GENERATOR)
            repo.write_output()
            revision = repo.commit()
            # When: the real checker regenerates the pushed revision in isolation.
            completed, result = run_gate(repo, repo.matrix())
        # Then: complete manifests match and the temporary clone is removed.
        self.assertEqual(0, completed.returncode, completed.stderr)
        self.assertEqual("CLEAN", result["classification"])
        self.assertEqual(revision, result["revision"])
        self.assertTrue(result["temporary_tree_removed"])
        pair = first_pair(result)
        self.assertEqual(pair["before_manifest_hash"], pair["after_manifest_hash"])
        self.assertEqual({"content": [], "missing": [], "mode": [], "type": [], "unexpected": []}, pair["changes"])

    def test_content_drift_when_committed_output_is_tampered(self) -> None:
        with DriftRepo() as repo:
            repo.write_generator(CLEAN_GENERATOR)
            repo.write_output("tampered\n")
            repo.commit()
            completed, result = run_gate(repo, repo.matrix())
        self.assertEqual(1, completed.returncode)
        self.assertEqual("GENERATED_DRIFT", result["classification"])
        pair = first_pair(result)
        self.assertEqual("CONTENT_DRIFT", pair["classification"])
        self.assertEqual(["generated/result.txt"], json_object(pair["changes"])["content"])

    def test_mode_drift_when_generator_changes_executable_bit(self) -> None:
        with DriftRepo() as repo:
            repo.write_generator("from pathlib import Path; p=Path('generated/result.txt'); p.chmod(0o755)\n")
            repo.write_output()
            repo.commit()
            completed, result = run_gate(repo, repo.matrix())
        self.assertEqual(1, completed.returncode)
        pair = first_pair(result)
        self.assertEqual("MODE_DRIFT", pair["classification"])
        self.assertEqual(["generated/result.txt"], json_object(pair["changes"])["mode"])

    def test_missing_and_unexpected_outputs_when_manifest_ownership_differs(self) -> None:
        for scenario in ("missing", "unexpected"):
            with self.subTest(scenario=scenario), DriftRepo() as repo:
                if scenario == "missing":
                    repo.write_generator(CLEAN_GENERATOR)
                else:
                    repo.write_generator(CLEAN_GENERATOR + "Path('generated/stale.txt').write_text('stale\\n')\n")
                    repo.write_output()
                repo.commit()
                completed, result = run_gate(repo, repo.matrix())
                pair = first_pair(result)
                changes = json_object(pair["changes"])
            self.assertEqual(1, completed.returncode)
            self.assertEqual("MISSING_OUTPUT" if scenario == "missing" else "UNEXPECTED_OUTPUT", pair["classification"])
            self.assertEqual(["generated/result.txt"] if scenario == "missing" else [], changes["missing"])
            self.assertEqual(["generated/stale.txt"] if scenario == "unexpected" else [], changes["unexpected"])

    def test_mtime_only_change_when_generator_touches_output(self) -> None:
        with DriftRepo() as repo:
            repo.write_generator("from pathlib import Path; Path('generated/result.txt').touch()\n")
            output = repo.write_output()
            repo.commit()
            os.utime(output, (1, 1))
            completed, result = run_gate(repo, repo.matrix())
        self.assertEqual(0, completed.returncode)
        self.assertEqual("CLEAN", result["classification"])

    def test_source_mutation_when_generator_writes_outside_owned_outputs(self) -> None:
        with DriftRepo() as repo:
            repo.write_generator(CLEAN_GENERATOR + "Path('source.txt').write_text('mutated\\n')\n")
            repo.write_output()
            repo.commit()
            completed, result = run_gate(repo, repo.matrix())
        self.assertEqual(1, completed.returncode)
        self.assertEqual("SOURCE_MUTATION", result["classification"])
        self.assertEqual(["source.txt"], first_pair(result)["source_mutations"])

    def test_generator_failure_and_timeout_when_command_does_not_complete(self) -> None:
        cases = ((["python3", "-c", "raise SystemExit(23)"], 2.0, "GENERATOR_FAILURE", 23),
                 (["missing-generated-drift-command"], 2.0, "GENERATOR_FAILURE", 127),
                 (["python3", "-c", "import time; time.sleep(30)"], 0.05, "GENERATOR_TIMEOUT", 124))
        for command, timeout, classification, exit_code in cases:
            with self.subTest(classification=classification), DriftRepo() as repo:
                repo.write_generator(CLEAN_GENERATOR)
                repo.write_output()
                repo.commit()
                completed, result = run_gate(repo, repo.matrix(command=command, timeout=timeout))
            self.assertEqual(1, completed.returncode)
            self.assertEqual(classification, result["classification"])
            self.assertEqual(exit_code, first_pair(result)["exit_code"])

    def test_real_checkout_is_unchanged_when_dirty_before_run(self) -> None:
        with DriftRepo() as repo:
            repo.write_generator(CLEAN_GENERATOR)
            output = repo.write_output()
            repo.commit()
            _ = output.write_text("pre-existing dirty\n", encoding="utf-8")
            os.chmod(output, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)
            before = (repo.git("status", "--porcelain=v1"), output.read_bytes(), output.stat().st_mode)
            completed, _result = run_gate(repo, repo.matrix())
            after = (repo.git("status", "--porcelain=v1"), output.read_bytes(), output.stat().st_mode)
        self.assertEqual(0, completed.returncode, completed.stderr)
        self.assertEqual(before, after)


if __name__ == "__main__":
    _ = unittest.main()
