import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { type RenderOptions, render } from "@testing-library/react";
import { NextIntlClientProvider } from "next-intl";
import type { ReactNode } from "react";

const TEST_MESSAGES = {
  landing: {
    nav: {
      changeLanguage: "Change language",
    },
    footer: {
      dashboard: "Dashboard",
      changelog: "Changelog",
      extension: "Chrome Extension",
      pricing: "Pricing",
      blog: "Blog",
      docs: "Documentation",
      github: "GitHub",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      tagline: "AI-powered content saving and knowledge management.",
      copyright: "All rights reserved.",
    },
  },
  dashboard: {
    sidebar: {
      nav: {
        dashboard: "Dashboard",
        articles: "Articles",
        shared: "Shared",
        changelog: "Changelog",
        settings: "Settings",
        billing: "Manage Billing",
        pricing: "Pricing",
      },
      user: {
        profile: "Profile",
        settings: "Settings",
        billing: "Manage Billing",
        help: "Help",
        feedback: "Feedback",
        logout: "Log out",
      },
    },
    overview: {
      title: "Dashboard",
      description: "Overview of your knowledge library.",
      savedArticles: "Saved Articles",
      aiSummaries: "AI Summaries",
      currentPlan: "Current Plan",
      viewArticlesTitle: "View Articles",
      viewArticlesDescription: "Browse and search your saved articles.",
      manageBillingTitle: "Manage Billing",
      manageBillingDescription: "View your plan and usage details.",
      installExtensionTitle: "Install Chrome Extension",
      installExtensionDescription: "Save content in one click while you browse.",
      recentArticlesTitle: "Recent Content",
      noRecentArticles: "No content saved yet.",
      viewAll: "View all",
      welcomeMessage: "Welcome back to NOD",
      heroTitlePrimary: "Content Insight",
      heroTitleAccent: "Workspace",
      heroSubtitle: "Save content, summarize with AI, and connect insights faster.",
      workflowTitle: "Today workflow",
      workflowStepCapture: "Capture content",
      workflowStepAnalyze: "Analyze summaries",
      workflowStepRefine: "Refine key insights",
      keyMetrics: "Key metrics",
      storageUnlimited: "Content storage is unlimited",
      usageCalculating: "Calculating usage...",
      planProActive: "Pro plan active",
      planFreeActive: "Using Free plan",
      quickActions: "Quick actions",
      getSupport: "Get support",
      openUsageGuide: "Open usage guide",
      modified: "Modified",
      justNow: "Just now",
      onboardingTitle: "Finish your onboarding!",
      onboardingDescription:
        "Connect your browser extension to start capturing insights instantly.",
      onboardingSetupNow: "Setup now",
      closeBanner: "Close banner",
    },
    searchPlaceholder: "Search...",
    statusLabel: "Status",
    markdownNote: "Note",
    copyAsMarkdown: "Copy as Markdown",
    copiedMarkdown: "Copied!",
    copyFailed: "Copy failed",
    myArticles: "My Articles",
    searchArticles: "Search articles...",
    allStatus: "All status",
    statusPending: "Pending",
    statusProcessing: "Processing",
    statusAnalyzing: "Analyzing",
    statusCompleted: "Completed",
    statusFailed: "Failed",
    loadingArticles: "Loading articles...",
    loadError: "Failed to load articles.",
    noArticles: "No articles yet. Save articles using the Chrome extension.",
    loadMore: "Load more",
    noSummary: "No summary available",
    openContent: "Open content",
    articleNotFound: "Article not found.",
    deleteConfirm: "Delete this article?",
    original: "Original",
    pendingAnalysis: "Waiting for analysis to start...",
    analyzingArticle: "AI is analyzing this article...",
    summaryInProgress: "Summarizing...",
    summary: "Summary",
    details: "Details",
    readTime: "~{minutes} min read",
    concepts: "Concepts",
    keyPoints: "Key Points",
    analyzedBy: "Analyzed by {provider}/{model}",
    similarArticles: "Similar Articles",
    loadingSimilar: "Loading similar articles...",
    similarity: "{percent}% match",
    allContentTypes: "All Types",
    typeTechBlog: "Tech Blog",
    typePaper: "Paper",
    typeNews: "News",
    typeDiscussion: "Discussion",
    typeGitHub: "GitHub",
    typeDocs: "Docs",
    typeVideo: "Video/Podcast",
    semanticSearch: "AI Search",
    searchMinChars: "Type at least 2 characters to search",
    articleListSubtitle: "Explore your saved content and quickly find the insight you need.",
    checkStatus: "Check Status",
    refreshing: "Refreshing...",
    retryAnalysis: "Retry",
    installExtensionCta: "Add to Chrome",
    shareActionLink: "Share",
    shareSectionTitle: "Share this summary",
    shareSectionDescription: "Generate a public link to share this article summary.",
    shareModalTitle: "Share this summary?",
    shareModalDescription: "Other people can view this content's AI summary through a public link.",
    shareModalIncludedTitle: "This shared link includes",
    shareModalIncludedSummary: "AI-generated summary",
    shareModalIncludedConcepts: "Core concepts",
    shareModalIncludedKeyPoints: "Key points",
    shareModalHint:
      "Only share this link with people you trust. Anyone with the link can read this summary.",
    shareUrlSettingsTitle: "URL settings",
    shareUseDefaultUrl: "Use default URL",
    shareSetCustomUrl: "Set custom URL",
    shareCustomUrlInputLabel: "Custom share URL",
    shareCustomUrlPlaceholder: "e.g. team-update",
    shareOgSettingsTitle: "Thumbnail image settings",
    shareUseDefaultOgImage: "Use default thumbnail",
    shareSetCustomOgImage: "Set custom OG image",
    shareCustomOgImageInputLabel: "Custom thumbnail URL",
    shareCustomOgImagePlaceholder: "https://...",
    shareGenerateLink: "Generate share link",
    shareRegenerateLink: "Regenerate share link",
    shareCopyLink: "Copy link",
    shareRevokeLink: "Revoke link",
    shareCopied: "Link copied",
    shareOpenPanel: "Open share panel",
    shareAdvanced: "Advanced share options",
    shareAlreadySharedTitle: "Share link created!",
    shareAlreadySharedDescription: "Copy the link below to share.",
    sharedTrustSummarizedBy: "Summarized by",
    sharedTrustFallbackName: "NOD User",
    sharedTrustOriginalLink: "View original",
    sharedCommentsTitle: "Comments",
    sharedCommentsAuthorLabel: "Name",
    sharedCommentsAuthorPlaceholder: "Your name",
    sharedCommentsContentLabel: "Comment",
    sharedCommentsContentPlaceholder: "Leave your reaction",
    sharedCommentsSubmit: "Add comment",
    sharedCommentsReplyAction: "Write reply",
    sharedCommentsAddReplyAction: "Reply",
    sharedCommentsActionMenuLabel: "Comment actions",
    sharedCommentsActionReport: "Report",
    sharedCommentsEditSave: "Save",
    sharedCommentsReplySubmit: "Reply",
    sharedCommentsReplyPlaceholder: "Write a reply",
    sharedCommentsSharerBadge: "Sharer",
    sharedCommentsHideReplies: "Hide replies",
    sharedCommentsReplyCountSingle: "reply",
    sharedCommentsReplyCountPlural: "replies",
    sharedCommentsEmpty: "No comments yet.",
    sharedCommentsSignInRequired: "Sign in to leave a comment.",
    sharedQuickActionEmpathy: "Empathy",
    sharedQuickActionComments: "Comments",
    sharedQuickActionShare: "Share",
    sharedShareCopyLink: "Copy link",
    sharedShareCopied: "Copied",
    sharedCommentsPanelTitle: "Responses ({count})",
    sharedCommentsPanelDescription: "View and write comments for this shared summary.",
    sharedCommentsSortLabel: "Sort by",
    sharedCommentsSortLatest: "Latest",
    sharedCommentsSortRecommended: "Recommended",
    sharedAuthSectionTitle: "Continue with your account",
    sharedAuthSectionDescription:
      "Sign in or sign up to save this shared summary to your own workspace.",
    viewOriginal: "View Original",
  },
  common: {
    loading: "Loading...",
    dashboard: "Dashboard",
    delete: "Delete",
    edit: "Edit",
    cancel: "Cancel",
    ok: "OK",
  },
  loginWelcome: "Welcome back",
  loginSubtitle: "Sign in to your NOD account",
  continueWithGoogle: "Continue with Google",
  login: {
    signingIn: "Signing in...",
    or: "or",
    backToHome: "Back to Home",
    highlightSave: "Save web articles with one click",
    highlightAnalyze: "AI automatically analyzes key insights",
    highlightSearch: "Find anything instantly with semantic search",
    secureNote: "Securely signed in with your Google account",
    signInTitle: "Sign in",
    signInSubtitle: "Sign in to continue building your knowledge library",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password",
    signInWithEmail: "Sign in with email",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    signUpLink: "Sign up",
    loginFailed: "Invalid email or password.",
    emailNotVerified: "Please verify your email first.",
  },
  signup: {
    title: "Sign up",
    subtitle: "Create your NOD account and start building your knowledge library",
    namePlaceholder: "Name",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password (8+ characters)",
    confirmPasswordPlaceholder: "Confirm password",
    createAccount: "Create account",
    creating: "Creating account...",
    hasAccount: "Already have an account?",
    signInLink: "Sign in",
    continueWithGoogle: "Sign up with Google",
    orDivider: "or",
    nameRequired: "Please enter your name.",
    emailInvalid: "Please enter a valid email address.",
    passwordMin: "Password must be at least 8 characters.",
    passwordMismatch: "Passwords do not match.",
    duplicateEmail: "This email is already registered.",
  },
  auth: {
    verifyEmail: {
      title: "Verify your email",
      description: "We sent a verification link to {email}. Please check your inbox.",
      resend: "Resend verification email",
      resent: "Verification email sent again.",
      backToLogin: "Back to login",
    },
    forgotPassword: {
      title: "Forgot password",
      subtitle: "Enter your email address and we'll send you a password reset link.",
      emailPlaceholder: "Email address",
      send: "Send reset link",
      sent: "Password reset link sent. Please check your inbox.",
      backToLogin: "Back to login",
      emailInvalid: "Please enter a valid email address.",
    },
    resetPassword: {
      title: "Set new password",
      subtitle: "Enter your new password below.",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      submit: "Change password",
      success: "Your password has been changed.",
      goToLogin: "Go to login",
      passwordMin: "Password must be at least 8 characters.",
      passwordMismatch: "Passwords do not match.",
    },
  },
  subscription: {
    basic: "Basic",
    pro: "Pro",
    usage: "Usage",
    unlimited: "Unlimited",
    summariesUsed: "{used}/{limit} summaries used",
    limitReached: "Limit reached",
  },
};

function createTestQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        gcTime: 0,
      },
      mutations: {
        retry: false,
      },
    },
  });
}

function TestProviders({ children }: { children: ReactNode }) {
  const queryClient = createTestQueryClient();
  return (
    <NextIntlClientProvider locale="en" messages={TEST_MESSAGES}>
      <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
    </NextIntlClientProvider>
  );
}

function renderWithProviders(ui: React.ReactElement, options?: Omit<RenderOptions, "wrapper">) {
  return render(ui, { wrapper: TestProviders, ...options });
}

export { renderWithProviders, createTestQueryClient, TestProviders };
